### ISSUE TITLE
Errors out on Dash 2.0

### ISSUE THREAD

**Issue by antoinerg** [plotly/dash-enterprise-auth#14]
The culprit is:
https://github.com/plotly/dash-enterprise-auth/blob/6e1aa59e315b6ae08da12febee523dbe57a92312/dash_enterprise_auth/__init__.py#L14

We will need to update this import definition in several of our libraries. @alexcjohnson is there a reference snippet on how to load `dcc` that works across Dash releases?

**Comment by alexcjohnson** [comment]
That causes an error? Should just be a warning, we have stub packages for the original top-level imports. What's the specific error you get?

In principle at some point we should update these, though that forces us to require dash >= 2. The new imports are:
```py
from dash import dcc, html, dash_table
```

**Comment by antoinerg** [comment]
Sorry for the noise. It is indeed only a warning.
