### ISSUE TITLE
 ModuleNotFoundError when I try to install with pip.

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/dash-enterprise-auth#2]
I'm getting the below error when I try `pip install --no-cache dash-enterprise-auth` into a virtualenv without dash-core-components. 
The error is coming because of this line https://github.com/plotly/dash-enterprise-auth/blob/master/setup.cfg#L3 since `pip install git+https://github.com/michaelbabyn/dash-enterprise-auth` works.
```
import dash_core_components as _dcc
    ModuleNotFoundError: No module named 'dash_core_components'
```

cc @T4rk1n

**Comment by T4rk1n** [comment]
> The error is coming because of this line https://github.com/plotly/dash-enterprise-auth/blob/master/setup.cfg#L3

Right the package is all in the init so it tries to import before being installed.
